import Link from 'next/link'
import { Sparkles } from 'lucide-react'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 sticky top-0 z-50">
        <div className="container mx-auto flex h-16 items-center justify-between px-4">
          <Link href="/" className="flex items-center gap-2">
            <Sparkles className="h-6 w-6 text-primary" />
            <span className="text-xl font-bold">Watkins AI</span>
          </Link>
        </div>
      </nav>

      <div className="container mx-auto px-4 py-16 max-w-3xl">
        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

        <div className="prose prose-gray max-w-none space-y-6 text-sm leading-relaxed text-muted-foreground">
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p>By accessing or using Watkins AI (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you are using the Service on behalf of an organization, you represent that you have the authority to bind that organization to these terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">2. Description of Service</h2>
            <p>Watkins AI is an AI-powered e-commerce growth platform that provides website analysis, automated email and SMS marketing, analytics and insights, product recommendations, customer support AI, website optimization, and done-for-you store building services. The specific features available to you depend on your subscription plan.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">3. Account Registration</h2>
            <p>You must provide accurate and complete information when creating an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">4. Subscription and Billing</h2>
            <p>Paid subscriptions are billed in advance on a monthly basis. You can upgrade, downgrade, or cancel your subscription at any time from your billing dashboard. Downgrades and cancellations take effect at the end of the current billing period. Refunds are provided at our discretion. We reserve the right to change pricing with 30 days&apos; notice.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">5. Free Trial</h2>
            <p>New accounts receive a 14-day free trial with full access to plan features. No credit card is required for the trial. At the end of the trial, your account will be downgraded to the Free plan unless you subscribe to a paid plan.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">6. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 mt-2 space-y-1">
              <li>Use the Service for any unlawful purpose or in violation of any regulations</li>
              <li>Attempt to gain unauthorized access to any part of the Service</li>
              <li>Interfere with or disrupt the Service or its infrastructure</li>
              <li>Upload malicious code, spam, or harmful content through the Service</li>
              <li>Resell, sublicense, or redistribute the Service without authorization</li>
              <li>Exceed your plan&apos;s usage limits through automated or abusive means</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">7. Intellectual Property</h2>
            <p>You retain ownership of all data you provide to the Service. Content generated by our AI (including optimized product descriptions, email content, and marketing materials) is owned by you once generated. The Service itself, including its software, design, and documentation, remains the intellectual property of Watkins AI.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">8. AI-Generated Content</h2>
            <p>Content produced by our AI systems is generated based on your inputs and store data. While we strive for accuracy and quality, AI-generated content should be reviewed before use. We are not responsible for any inaccuracies, legal issues, or damages arising from the use of AI-generated content without review.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">9. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, Watkins AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or business opportunities, arising from your use of the Service. Our total liability shall not exceed the amount paid by you in the 12 months preceding the claim.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">10. Termination</h2>
            <p>We may suspend or terminate your account if you violate these terms. You may delete your account at any time. Upon termination, your data will be retained for 30 days to allow for export, after which it will be permanently deleted.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">11. Changes to Terms</h2>
            <p>We may update these Terms of Service at any time. Material changes will be communicated via email or an in-app notice at least 30 days before they take effect. Continued use of the Service after changes constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">12. Contact</h2>
            <p>For questions about these Terms, contact us at <a href="mailto:legal@watkinsai.com" className="text-primary hover:underline">legal@watkinsai.com</a>.</p>
          </section>
        </div>
      </div>
    </div>
  )
}
